name: Feature request
description: Create a feature request
title: "[feat]: "
labels: enhancement
body:
    - type: textarea
      id: feature-description
      attributes:
          label: Feature description
          description: Tell us about your feature request
          placeholder: "I think this feature would be great because..."
      validations:
          required: true

    - type: textarea
      id: context
      attributes:
          label: Additional Context
          description: Add any other context about the feature here.
          placeholder: ex. screenshots, Stack Overflow links, forum links, etc.
      validations:
          required: false
